### Suche alle Kunden
http://{{host}}/customer

### Suche Kunden mit bestimmtem Vornamen und Nachnamen
http://{{host}}/customer?firstName=Manuel&lastName=Neuer

### Suche Kunden mit bestimmtem Vornamen und Nachnamen
http://{{host}}/customer?firstName=Manuel&lastName=Ne

### Füge einen neuen Kunden hinzu
POST http://{{host}}/customer?firstName=Manuel&lastName=Neuer
Content-Type: application/json

< kunde-neu.json

### Überprüfe die Kreditwürdigkeit eines Kunden
POST http://{{host}}/customer?credit=100
Content-Type: application/json

< kunde-neu.json

### Überprüfe die Kreditwürdigkeit eines Kunden
POST http://{{host}}/customer?credit=100000
Content-Type: application/json

< kunde-neu.json

###
